"""Change completed column to complete

Revision ID: feed94de5542
Revises: 95f0eda9fe14
Create Date: 2025-03-02 22:19:43.706563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feed94de5542'
down_revision: Union[str, None] = '95f0eda9fe14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False, server_default='false'))
    op.execute('UPDATE todos SET complete = completed')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
